### ISSUE TITLE
Error handing missing for RemoteReporter TimerTask

### ISSUE THREAD

**Issue by hzariv** [uber/jaeger-client-java#116]
In the following code for TimerTask, ArrayBlockingQueue could throw exceptions such as IllegalStateException and so on but the code is not catching and logging these errors properly. Code should catch and log proper exceptions via slf4j logger and may be capture this error in some metrics.

https://github.com/uber/jaeger-client-java/blob/ebda740068a0568650f321f56db6c2b658cb0e99/jaeger-core/src/main/java/com/uber/jaeger/reporters/RemoteReporter.java#L72

Exception in thread "Timer-3" java.lang.IllegalStateException: Queue full
at java.util.AbstractQueue.add(AbstractQueue.java:98)
at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312)
at com.uber.jaeger.reporters.RemoteReporter$1.run(RemoteReporter.java:73)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)

**Comment by yurishkuro** [comment]
Good catch, @hzariv 

I think this needs a bit of refactoring too. In `close()` method we should be using blocking `put`, but in `report()` and timer we can use `add()` and catch state exception. I don't think we need to log anything. We already increment metric in `report()`, it just needs to happen in `catch` clause. As for failing to add flush command - I'd just swallow that exception, the client should be already alerting on the dropped metric.
