### ISSUE TITLE
Flaky RemoteReporter test

### ISSUE THREAD

**Issue by yurishkuro** [uber/jaeger-client-java#184]
https://travis-ci.org/uber/jaeger-client-java/jobs/232521027#L863

```
com.uber.jaeger.reporters.RemoteReporterTest > testFlushUpdatesQueueLength FAILED
    java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at com.uber.jaeger.reporters.RemoteReporterTest.testFlushUpdatesQueueLength(RemoteReporterTest.java:213)
```

**Comment by mabn** [comment]
Oops, I forgot that TimerTask starts with 0 delay and can call `flush()` earlier. I'll create some PR with a fix.
